### ISSUE TITLE
Failed to set up: check the logs

### ISSUE THREAD

**Issue by sparky-vision** [finity69x2/nws_alerts#117]
NWS alerts was recently working, but it seems to have stopped very recently, though I'm not sure when.

The logs:

```
Error setting up entry NWS Alerts for nws_alerts

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 751, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nws_alerts/__init__.py", line 71, in async_setup_entry
    coordinator = AlertsDataUpdateCoordinator(
        hass,
    ...<2 lines>...
        config_entry.data.get(CONF_INTERVAL),
    )
  File "/config/custom_components/nws_alerts/__init__.py", line 149, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        hass,
        ^^^^^
    ...<3 lines>...
        update_interval=self.interval,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 139, in __init__
    self.config_entry.async_on_unload(self.async_shutdown)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'mappingproxy' object has no attribute 'async_on_unload'
```

Installation method Home Assistant OS
Core 2025.9.4
Supervisor 2025.09.0
Operating System 16.2
Frontend 20250903.5

**Comment by Nameless11111** [comment]
Stopped for me today right after updating to 6.2 and rebooting.
In Core 2025.8.3

**Comment by mattmeiser** [comment]
Broken in 2025.10.0b4 as well, downgrading to 6.1 works there as well.

**Comment by JCummings49** [comment]
Same issue here.

**Comment by dbullendsl** [comment]
Same issue, revert back to previous version works
